# Generated by Django 2.1.3 on 2018-11-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('MODE', models.CharField(default='Wifi Station', max_length=20)),
                ('SSID', models.CharField(default='Thanh Thao_plus', max_length=50)),
                ('PSK', models.CharField(default='chaobuoisang', max_length=50)),
                ('IP', models.CharField(default='192.168.2.1', max_length=20)),
                ('GateWay', models.CharField(default='192.168.2.1', max_length=20)),
                ('SubnetMask', models.CharField(default='255.255.255.0', max_length=20)),
                ('IP_Mode', models.CharField(default='DHCP', max_length=20)),
                ('SignalStrength', models.CharField(default='Good', max_length=10)),
                ('Update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
